### ISSUE TITLE
A question: Why is this `blockingGet`

### ISSUE THREAD

**Issue by fadi-botros** [Ahmed-Adel-Ismail/Open-Weather-Maps#1]
https://github.com/Ahmed-Adel-Ismail/Open-Weather-Maps/blob/c74f7edb46e6bb445fc153197fb4dd1389131946/app/src/main/java/com/reactive/owm/domain/server/AppKeyInterceptor.java#L23-L29

Couldn't the function itself return Observable<Response>, and you wouldn't block anything?
I think the main Reactive goal is Vertx's logo "Don't block me".

Please don't be aggressive in reply, I maybe naïve in this question

**Comment by Ahmed-Adel-Ismail** [comment]
This is an OkHttp "Interceptor", it is not an option to return any thing but a "Response"

This interceptor is invoked on every request in a blocking manner by the library, it is not my choice here
